use_frameworks!

platform :ios, '8.0'

target 'AMPProgressHUD_Example' do
  pod 'AMPProgressHUD', :path => '../'
  
  target 'AMPProgressHUD' do
    pod 'MBProgressHUD'
    
  end

  target 'AMPProgressHUD_Tests' do
    inherit! :search_paths

    
  end
end
